// Theme tokens for the /services page. Mirrors the pattern in app/theme.ts but
// carries the richer token set this page's design (nav, pricing cards, table,
// accordion, chips) needs. Kept separate so the home page's theme.ts stays untouched.

const light = {
  pageBg: "bg-white text-[#0B1220]",
  navBg: "border-b border-gray-200 bg-white/90 backdrop-blur-md",
  navBgFloating: "border-b border-white/20 bg-white/40 backdrop-blur-md",
  navLink: "text-gray-600 hover:text-[#0B1220]",
  eyebrow: "text-cyan-700",
  heading: "text-[#0B1220]",
  headingAccent: "text-cyan-600",
  body: "text-gray-600",
  faint: "text-gray-500",
  cardBg: "border border-gray-200 bg-white shadow-sm",
  cardBgAlt: "border border-gray-200 bg-gray-50",
  iconCircle: "border border-cyan-100 bg-cyan-50",
  chip: "border border-gray-200 bg-white text-gray-700",
  checkIcon: "text-cyan-600",
  dashIcon: "text-gray-300",
  tableHeadBg: "bg-gray-50 text-gray-500",
  tableBorder: "divide-gray-100 border-gray-200",
  tableRowHover: "hover:bg-gray-50/80",
  tableHighlight: "bg-cyan-50 text-[#0B1220]",
  accordionBorder: "border-gray-200",
  accordionHover: "hover:bg-gray-50",
  divider: "border-gray-200",
  footerBg: "border-t border-gray-200 bg-white text-gray-500",
  ctaPrimary: "bg-[#69E8FF] text-[#0B1220] hover:brightness-95",
  ctaSecondary: "border border-gray-300 text-[#0B1220] hover:bg-gray-50",
  heroOverlay: "",
  contactOverlay: "",
};

const dark = {
  pageBg: "bg-[#0f1115] text-white",
  navBg: "border-b border-white/10 bg-[#0f1115]/90 backdrop-blur-md",
  navBgFloating: "border-b border-white/10 bg-[#0f1115]/35 backdrop-blur-md",
  navLink: "text-white/70 hover:text-white",
  eyebrow: "text-[#69E8FF]",
  heading: "text-white",
  headingAccent: "text-[#69E8FF]",
  body: "text-white/70",
  faint: "text-white/55",
  cardBg: "border border-white/10 bg-white/5",
  cardBgAlt: "border border-white/10 bg-[#141821]",
  iconCircle: "border border-white/10 bg-white/5",
  chip: "border border-white/10 bg-white/5 text-white/80",
  checkIcon: "text-[#69E8FF]",
  dashIcon: "text-white/25",
  tableHeadBg: "bg-white/5 text-white/60",
  tableBorder: "divide-white/10 border-white/10",
  tableRowHover: "hover:bg-white/[0.04]",
  tableHighlight: "bg-[#69E8FF]/10 text-white",
  accordionBorder: "border-white/10",
  accordionHover: "hover:bg-white/5",
  divider: "border-white/10",
  footerBg: "border-t border-white/10 bg-[#0f1115] text-white/55",
  ctaPrimary: "bg-[#69E8FF] text-[#0B1220] hover:brightness-95",
  ctaSecondary: "border border-white/15 text-white hover:bg-white/10",
  heroOverlay: "bg-gradient-to-r from-[#0f1115] via-[#0f1115]/75 to-transparent",
  contactOverlay: "bg-gradient-to-t from-[#0f1115] via-[#0f1115]/60 to-transparent",
};

export const servicesThemes = { dark, light };
export type ServicesTheme = typeof dark;
